package com.example.cloudBalance.cloudBalance.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    INVALID_ROLE,
    UNAUTHORIZED,
    VALIDATION_FAILED,
    INTERNAL_ERROR,
    INVALID_SESSION,
    SESSION_EXPIRED,
    ACCOUNT_REQUIRED,
    REFRESH_TOKEN_MISSING,
    INVALID_ARGUMENTS,
    NOT_FOUND,
    ACCOUNT_NOT_FOUND,
    FILTER_NOT_FOUND,
    SESSION_NOT_FOUND,
    ACCOUNT_ALREADY_EXISTS
}
